### ISSUE TITLE
KeyError: 'optimizer_state' with the published weights

### ISSUE THREAD

**Issue by n-patiphon** [er-muyue/BeMapNet#6]
Thank you for opening this to the public. Greate work!

I tried testing the published weight but couldn't get it to work. The error is as follows:
```
2023-08-23 15:46:08.332 | INFO     | ...engine.callbacks:load_checkpoint:110 - Loading parameters from checkpoint assets/weights/bemapnet_nuscenes_swint_ep110_model.pth
.../site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
assets/weights/upernet_swin_tiny_patch4_window7_512x512.pth
Backbone missing_keys: []
Backbone unexpected_keys: ['norm0.weight', 'norm0.bias']
Traceback (most recent call last):
  File "configs/bemapnet_nuscenes_swint.py", line 314, in <module>
    BeMapNetCli(Exp).run()
  File ".../engine/core.py", line 172, in run
    self.dispatch(self.executor)
  File ".../engine/core.py", line 169, in dispatch
    executor_func()
  File ".../engine/core.py", line 148, in executor
    self.get_evaluator().eval()
  File ".../engine/core.py", line 190, in get_evaluator
    evaluator = BeMapNetEvaluator(exp=exp, callbacks=callbacks, logger=logger)
  File ".../engine/executor.py", line 190, in __init__
    super(BeMapNetEvaluator, self).__init__(exp, callbacks, logger)
  File ".../engine/executor.py", line 61, in __init__
    self._invoke_callback("load_checkpoint")
  File ".../engine/executor.py", line 93, in _invoke_callback
    func(self, *args, **kwargs)
  File ".../engine/callbacks.py", line 134, in load_checkpoint
    trainer.optimizer.load_state_dict(checkpoint["optimizer_state"])
KeyError: 'optimizer_state'
```

**Comment by er-muyue** [comment]
Thanks for pointing out this bug. I've fixed [it](https://github.com/er-muyue/BeMapNet/blob/7213e6c2b9982054da37c5ba39dbb72499cddf32/bemapnet/engine/callbacks.py#L134) and now you should be able to test BeMapNet with our published weights.
